# Generated by Django 3.0.4 on 2020-03-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0003_auto_20200317_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbif',
            name='acceptedNameUsage',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='acceptedTaxonKey',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='classKey',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='coordinateUncertaintyInMeters',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='day',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='decimalLatitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='decimalLongitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='depth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='endDayOfYear',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='familyKey',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='gbifID',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='genusKey',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='georeferencedDate',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='kingdomKey',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='month',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='orderKey',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='phylumKey',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='speciesKey',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='startDayOfYear',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='taxonKey',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gbif',
            name='year',
            field=models.BigIntegerField(null=True),
        ),
    ]
