# Generated by Django 3.0.4 on 2020-03-17 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biodiversity', '0005_auto_20200317_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbif',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
